name: Release npm package

on:
    push:
        branches:
            - master

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@v1
              with:
                  node-version: '15'
            - run: yarn install
            - run: yarn build:hooks
            - run: yarn workspaces foreach run semantic-release -e semantic-release-monorepo
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
