name: Release npm package

on:
    push:
        branches:
            - master

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@v1
              with:
                  node-version: '15'
            - run: yarn install
            - run: yarn build:hooks
            - run: yarn build:components
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            - run: yarn release:hooks
            - run: yarn release:components
