name: test
on: [push]
jobs:
    test-contracts:
        runs-on: macos-11
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '15'
            - run: yarn install
            - run: yarn test
